### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bwolfson97** [bwolfson97/plant_pathology#3]
### TODO:
- [x] Write wrapper around `model.predict()` to decode probabilities
- [ ] Update image to show model's prediction with bar chart
- [ ] Add Colab notebook
- [ ] Add further improvements section
- [ ] Fix image on PyPi
